Taking aboard the last refugees from medium.
mizool/mizool pull request #176
Opened 2020-11-11 13:47 UTC by JanDoerrenhaus

2020-11-12 11:28 UTC, schroenser approved these changes
Since the files were merely moved from medium to here, I'm choosing to ignore the sonar problems in this pull request.
If the fixes were easy enough to simply perform them while making this move, we would probably have applied them in medium alreay.

2020-11-19 08:28 UTC, bannmann requested changes

2020-11-19 08:28 UTC, bannmann commented on technology/gson/src/test/java/com/github/mizool/technology/gson/TestGsonMessageBodyHandler.java
> +        ;
remove this line and the blank line above

2020-11-19 14:02 UTC, bannmann approved these changes

2020-11-19 14:03 UTC, merged